
spring:
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    platform: h2
    url: jdbc:h2:tcp://localhost//D:/h2/mtkj
    username: root
    password: root
    driver-class-name: org.h2.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  servlet:
    context-path: /demo
logging:
  level:
    cn.zdxh.mtkj.dataobject.mapper: trace
